### ISSUE TITLE
Only in /home/yoh/deb/gits/pkg-exppsy/dcm_qa/Ref: fMRI_MB_int_26.{json,nii}

### ISSUE THREAD

**Issue by yarikoptic** [neurolabusc/dcm_qa#5]
sorry to be the pain... dcm2niix v1.0.20170623, this repo 01fd3df7435d19dcfb65d5776bf9bb473bfa57e2
```shell
Running command:
diff -br /home/yoh/deb/gits/pkg-exppsy/dcm_qa/Out /home/yoh/deb/gits/pkg-exppsy/dcm_qa/Ref -I ConversionSoftwareVersion
Only in /home/yoh/deb/gits/pkg-exppsy/dcm_qa/Ref: fMRI_MB_int_26.json
Only in /home/yoh/deb/gits/pkg-exppsy/dcm_qa/Ref: fMRI_MB_int_26.nii
```

**Comment by neurolabusc** [comment]
This is as a valid error, and indeed the reason I included sample JPEG2000 images. This warning suggests you are testing a copy of dcm2niix compiled without JPEG2000 support. Therefore, your copy failed to convert the images jp2k1.dcm and jp2k2.dcm. One solution is to get  a [pre-compiled release](https://github.com/rordenlab/dcm2niix/releases), alternatively you can build a copy with `cmake -DBATCH_VERSION=ON ..` or create a [custom JPEG2000](https://github.com/rordenlab/dcm2niix/blob/master/COMPILE.md) build.

**Comment by yarikoptic** [comment]
hmm... it as built with BATCH_VERSION=ON:

```shell
$> grep BATCH dcm2niix_1.0.20170623-1_amd64.build
  -DBATCH_VERSION:BOOL=ON
	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DUSE_STATIC_RUNTIME:BOOL=OFF -DUSE_SYSTEM_TURBOJPEG:BOOL=ON -DUSE_SYSTEM_ZLIB:BOOL=ON -DBATCH_VERSION:BOOL=ON
cd /home/yoh/deb/gits/pkg-exppsy/build-area/dcm2niix-1.0.20170623/build/console-build && /usr/bin/cmake -Wno-dev --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX=/home/yoh/deb/gits/pkg-exppsy/build-area/dcm2niix-1.0.20170623/build -DUSE_STATIC_RUNTIME:BOOL=OFF -DUSE_SYSTEM_ZLIB:BOOL=ON -DUSE_SYSTEM_TURBOJPEG:BOOL=ON -DUSE_SYSTEM_JASPER:BOOL= -DUSE_OPENJPEG:BOOL=OFF -DOpenJPEG_DIR:PATH= -DBATCH_VERSION:BOOL=ON -DYAML-CPP_DIR:PATH=/cmake/yaml-cpp "-GUnix Makefiles" /home/yoh/deb/gits/pkg-exppsy/build-area/dcm2niix-1.0.20170623/console

$> apt-cache policy dcm2niix
dcm2niix:
  Installed: 1:1.0.20170623-1
  Candidate: 1:1.0.20170623-1
  Version table:
 *** 1:1.0.20170623-1 100
        100 /var/lib/dpkg/status
```

may be you meant that I have to use USE_OPENJPEG instead of turbojpeg?

**Comment by neurolabusc** [comment]
Mea culpa, as described on the README.MD, to compile for OPENJPEG (which provides JPEG2000 support, classic JPEG and lossless ancient JPEG are different) you use:
```bash
mkdir build && cd build
cmake -DUSE_OPENJPEG=ON ..
make
```

**Comment by yarikoptic** [comment]
sorry for being a pain but FWIW -DUSE_OPENJPEG=ON -- still not sufficient ... built with it, verified that openjp is linked, still qa fails (see below). README suggests that I have to build openjpeg statically myself, but that shouldn't be required I hope
```shell
(git)hopa:~exppsy/dcm2niix/dcm_qa[master]git
$> grep USE_OPENJPEG ../../build-area/dcm2niix_1.0.20170624-1_amd64.build
      -DUSE_OPENJPEG:BOOL=ON \
	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DUSE_STATIC_RUNTIME:BOOL=OFF -DUSE_SYSTEM_TURBOJPEG:BOOL=ON -DUSE_OPENJPEG:BOOL=ON -DUSE_SYSTEM_ZLIB:BOOL=ON -DBATCH_VERSION:BOOL=ON
cd /home/yoh/deb/gits/pkg-exppsy/build-area/dcm2niix-1.0.20170624/build/console-build && /usr/bin/cmake -Wno-dev --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX=/home/yoh/deb/gits/pkg-exppsy/build-area/dcm2niix-1.0.20170624/build -DUSE_STATIC_RUNTIME:BOOL=OFF -DUSE_SYSTEM_ZLIB:BOOL=ON -DUSE_SYSTEM_TURBOJPEG:BOOL=ON -DUSE_SYSTEM_JASPER:BOOL= -DUSE_OPENJPEG:BOOL=ON -DOpenJPEG_DIR:PATH=/usr/lib/x86_64-linux-gnu/openjepg-2.1 -DBATCH_VERSION:BOOL=ON -DYAML-CPP_DIR:PATH=/cmake/yaml-cpp "-GUnix Makefiles" /home/yoh/deb/gits/pkg-exppsy/build-area/dcm2niix-1.0.20170624/console
2 23015.....................................:Sat 24 Jun 2017 07:08:42 AM PDT:.
(git)hopa:~exppsy/dcm2niix/dcm_qa[master]git
$> ldd /usr/bin/dcm2niix                                                 
	linux-vdso.so.1 (0x00007ffeea7e6000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f962b807000)
	libturbojpeg.so.0 => /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 (0x00007f962b594000)
	libopenjp2.so.7 => /usr/lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f962b359000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f962afd7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f962acd3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f962aaba000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f962a71c000)
	/lib64/ld-linux-x86-64.so.2 (0x000055d0bde96000)
2 23016.....................................:Sat 24 Jun 2017 07:08:48 AM PDT:.
(git)hopa:~exppsy/dcm2niix/dcm_qa[master]git
$> rm -rf Out/; ./batch.sh 2>&1 | tail -n 5                              

Running command:
diff -br /home/yoh/deb/gits/pkg-exppsy/dcm2niix/dcm_qa/Out /home/yoh/deb/gits/pkg-exppsy/dcm2niix/dcm_qa/Ref -I ConversionSoftwareVersion
Only in /home/yoh/deb/gits/pkg-exppsy/dcm2niix/dcm_qa/Ref: fMRI_MB_int_26.json
Only in /home/yoh/deb/gits/pkg-exppsy/dcm2niix/dcm_qa/Ref: fMRI_MB_int_26.nii

2 23018.....................................:Sat 24 Jun 2017 07:09:11 AM PDT:.
(git)hopa:~exppsy/dcm2niix/dcm_qa[master]git
$> dcm2niix --version
Chris Rorden's dcm2niiX version v1.0.20170624 (OpenJPEG build) GCC6.3.0 (64-bit Linux)
Example output filename: '/MPRAGE_1.nii'
```

**Comment by ningfei** [comment]
If you do want to use your own build of dcm2niix, please comment out [Line 45-48](https://github.com/rordenlab/dcm2niix/blob/master/SuperBuild/SuperBuild.cmake#L45-L48) in `SuperBuild.cmake`, thus force building OpenJPEG from github and linking to it statically.
Another option would be: uninstall your local installation of libeopenjp2, which might be incompatible. Although the version you installed is probably also v2.1/v2.0...

**Comment by yarikoptic** [comment]
I want my own build of dcm2niix but not of openjpeg, which I want to use the one installed system-wide. 
I have 2.1.2 version of libopenjp2.

**Comment by neurolabusc** [comment]
The [compile.md](https://github.com/rordenlab/dcm2niix/blob/master/COMPILE.md) provides several recipes for compiling custom variations of dcm2niix, including those with JPEG2000. Check your compiler for details on how to build with dynamic libraries relative to static builds. In general, I would highly discourage the use of JPEG2000 as a DICOM transfer syntax, and suspect it will greatly complicate archival studies. To my knowledge, dcm2niix is the only open source DICOM tool to support this transfer syntax. The only commercial tools that use this are DCMJP2K and Osirix (via its usage of DCMJP2K). Unfortunately, JPEG2000 as a standard saw little adoption, despite being somewhat better than classic JPEG. In my experience the two open source implementations were either slow, poorly documented, cumbersome (OpenJPEG) or unsuitable for high-bit depth DICOM (JASPER). Now that HEIF is here, I think that any opportunity JPEG2000 had to gain traction is long since past. Therefore, I think it is completely reasonable to compile dcm2niix without JPEG2000 support. It does provide clear feedback when it detects an offending image. For Unix users with a C compiler installed, you can compile dcm2niix by simply typing "make" in the "console" folder.

**Comment by ningfei** [comment]
@yarikoptic it will probably work if you use 2.1.0 version of libopenjp2. That's why I fixed the external build of the openjpeg library to a specific commit. Something is broken in newer version.
Support of JPEG2000 is somehow really troublesome. I recently got some JPEG2000 lossless DICOMs from GE machine, in which the offset tables are problematic. For another dataset with the same transfer syntax, it also failed when I tried (with different tools) to convert the DICOMs to nifti. Feels like these JPEG2000 DICOMs were produced using different standards. Besides, the API of OpenJPEG seems changing with versions. Even within the same version, there might be compatibility issue if you use the code from different commits.

**Comment by ningfei** [comment]
Hi @yarikoptic, confirmed that dcm2niix doesn't work with libopenjp2 if the library is built using code after [this](https://github.com/uclouvain/openjpeg/commit/237ddd72f15fffe26e446604b2019604d9ae5211) commit. Any version larger than 2.1.0 is affected. As far as I see, we can't solve this on dcm2niix side. Chris just created an issue report [here](https://github.com/uclouvain/openjpeg/issues/962). You may either install 2.1.0 version of libopenjp2 or build it on the fly when buiding dcm2niix.

**Comment by neurolabusc** [comment]
@yarikoptic and @ningfei - can you please test the latest master of dcm2niix. This should work with modern versions of dcm2niix. My fault entirely, I am afraid.

**Comment by ningfei** [comment]
@neurolabusc - tested with openjpeg v2.1.2, works now without problem!

**Comment by neurolabusc** [comment]
Great. I have tested it with Debian Linux using the current [origin master](https://github.com/uclouvain/openjpeg) 2.2.0. To use the 2.2.0 branch you need to compile with `-lpthreads` - I have noted this in the [COMPILE.md](https://github.com/rordenlab/dcm2niix/blob/master/COMPILE.md), but perhaps something that could be incorporated into your build files. Perhaps @TheChymera can test for gentoo.

**Comment by TheChymera** [comment]
before I can test this I need to package `dcm2niix`.

**Comment by yarikoptic** [comment]
FWIW -- seems to work for me on my Debian box now... I will build with openjpeg support and upload to neurodebian shortly
