### ISSUE TITLE
Get some multi-echo samples

### ISSUE THREAD

**Issue by yarikoptic** [neurolabusc/dcm_qa#8]
E.g. here is one (non functional, so somewhat not that interesting):
http://datasets.datalad.org/?dir=/dicoms/dartmouth-phantoms/bids_test6-PD+T2w/

ATM there seems to be none:
```shell
$> git show-ref HEAD
c7bab67f14105031776e194d47961749f264e209 refs/remotes/origin/HEAD
$> git grep EchoNumber
```
and it would be great to test/make sure that dcm2niix could work consistently across different manufacturers (ref issue in heudiconv: https://github.com/nipy/heudiconv/issues/162#issuecomment-385412124)

I could provide more samples from Siemens but unfortunately we do not have any EPI multi-echo sequences I believe :-/

**Comment by neurolabusc** [comment]
@yarikoptic - the current dcm_qa is designed to simulate problematic datasets or rich details. Since we test every build of dcm2niix (separately for Windows, MacOS, Linux), I have tried to keep the disk requirements small. 

I can see the value of an expanded testing dataset, but I do not think that Github is the correct platform for this. I have not had time to investigate, but DataLad or GitLab may be better ways to host larger datasets. 

I would suggest you fork dcm_qa - either on Github or another platform. I would be happy switch dcm2niix to test your more extensive battery once it is validated.
 
The [dcm2niix wiki](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging) includes diffusion examples from GE, Siemens and Philips. Hopefully, we will have some new [modern Philips DTI scans soon](https://github.com/rordenlab/dcm2niix/issues/182).

For images, I would prefer using a human head over phantoms: these allow you to infer image rotations and bvec calculations. I would also suggest placing a fiducial marker on one hemisphere (you can see a saline bag on the left temple in several of the linked datasets).

**Comment by neurolabusc** [comment]
@yarikoptic - I acquired 3 different forms of [https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Multi-Echo_MRI multi-echo MRI] for validation. First, field maps are the Siemens Product and are saved as 2D slices. Second, the CMRR research EPI T2* fMRI/resting state sequences saved as mosaics. Finally, the MGH MEMPRAGE T1 scans. The samples proved useful already - I already made changes to dcm2niix. I do think these require too much disk space for dcm_qa, but would be useful for a future testing repository.

**Comment by yarikoptic** [comment]
Great, thanks! 
If you are interested to go git-annex (what datalad uses) route for the ultimate collection, I would be happy to help to establish it. git-annex on Windows is a bit of a pain but for this minimal purpose of his getting the content, it should suffice.
We could host content somewhere or even just use https://web.gin.g-node.org which does provide some storage and supports git annex... Main clone of the repository could still reside on GitHub, just content live elsewhere .

**Comment by neurolabusc** [comment]
I honestly have too much on my plate to curate this at the moment. If you want to step up to the challenge, you can merge dcm_qa with the files at the [dcm2niix wiki](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii). I am sure many will find it useful.
